### ISSUE TITLE
Написать тесты для проекта.

### ISSUE THREAD

**Issue by Whitetech7417** [Students-of-the-city-of-Kostroma/16ISb#4]
Включая большое количество необходимых исключений , вариантов развития событий - учесть множество возможных вариантов.
К примеру: создаем проект(console app) в нём пишем. ТО что поступает на вход = ТО что выдает программа = ТО что ожидается на выходе. Какой метод в классе будет отвечать за выполнение я скину чуть позже. класс залью на гит.

**Comment by Lewwwka** [comment]
+ тесты
[Мега тесты.docx](https://github.com/Students-of-the-city-of-Kostroma/16ISb/files/1987541/default.docx)

**Comment by Lewwwka** [comment]
+Кидаю супер гайд по созданию тестов (https://youtu.be/p3EUhUjv2LM)
